# local.conf (debian12computenode)
# Fichero de configuracion utilizado por Devstack para personalizar el despliegue
# del nodo de computo. Sobrescribe valores por defecto definidos en stack.sh.

[[local|localrc]]

# Direccion IP principal
HOST_IP=192.168.13.12

# Rango de direcciones IP que usaran las instancias en la red privada
FIXED_RANGE=10.4.128.0/20

# Rango de direcciones IP flotantes disponibles para asignar desde la red publica
FLOATING_RANGE=192.168.13.128/26

# Path de log
LOGFILE=/opt/stack/logs/stack.sh.log

# Credenciales
ADMIN_PASSWORD=X
DATABASE_PASSWORD=X
RABBIT_PASSWORD=X
SERVICE_PASSWORD=X
SERVICE_PASSWORD=X

#Base de datos
DATABASE_TYPE=mysql

#Direccion donde se encuentran los servicios principales (nodo controlador)
SERVICE_HOST=192.168.13.11
MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOSTPORT=$SERVICE_HOST:9292

# Servicios que tendra el nodo de computo
ENABLED_SERVICES=n-cpu,c-vol,placement-client,ovn-controller,ovs-vswitchd,ovsdb-server,q-ovn-metadata-agent

NOVA_VNC_ENABLED=True

# URL del proxy VNC que se encuentra en el nodo controlador
NOVNCPROXY_URL="http://$SERVICE_HOST:6080/vnc_lite.html"

VNCSERVER_LISTEN=$HOST_IP
VNCSERVER_PROXYCLIENT_ADDRESS=$VNCSERVER_LISTEN
