# local.conf
# Sobrescribe valores por defecto definidos en stack.sh.
# Permite ajustar en la instalacion diferentes parametros
# como IPs, rangos de red, passwords, etc.

[[local|localrc]]

# IP principal de la VM controlador
HOST_IP=192.168.13.11

# Rango de IPs privadas
FIXED_RANGE=10.4.128.0/20

# Rango de IPs flotantes
FLOATING_RANGE=192.168.13.128/26

# Path de log
LOGFILE=/opt/stack/logs/stack.sh.log

# Credenciales
ADMIN_PASSWORD=X
DATABASE_PASSWORD=X
RABBIT_PASSWORD=X
SERVICE_PASSWORD=X
